# .github/workflows/app.yaml
name: Ref Syntax Check Automation

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'models/**/*.sql'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ref-syntax-checking-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Fetch base commit
        run: git fetch origin ${{ github.event.pull_request.base.sha }}

      - name: Fetch head commit
        run: git fetch origin ${{ github.event.pull_request.head.sha }}

      - name: Get code diff
        shell: bash
        run: |
          git diff ${{ github.event.pull_request.base.sha}}..${{ github.event.pull_request.head.sha }} models/**/*.sql | grep '^\+ ' > scripts/new_lines.txt

      - name: Run validations
        id: validations
        run: python scripts/check_ref_syntax.py --file_name scripts/new_lines.txt
